apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: smynjjesz-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-3b215fdfdc.dcpy.p3.openshiftapps.com/rhtap/rhtap-qe-java-springboot:7c665e2e078eb2c2ca9c27764f408a1689cda967@sha256:e8ff5e2c2362eab313c35e6cb1fd30987f42bf0f9313715492aabb2edae614c1
          name: container-image
